namespace Popstation
{
    public enum PopstationEventEnum
    {
        WritePbpHeader,
        WriteSfo,
        WriteHeader,
        WriteBootPng,
        WriteIndex,
        WriteIso,
        WriteIcon0Png,
        WriteIcon1Pmf,
        WritePic0Png,
        WritePic1Png,
        WriteSnd0At3,
        WriteDataPsp,
        WritePsTitle,
        WriteIsoHeader,
        WriteProgress,
        WriteSize,
        WriteStart,
        UpdateIndex,
        WriteSpecialData,
        WriteToc,
        GetIsoSize,
        ExtractProgress,
        ConvertProgress,
        ConvertSize,
        ConvertComplete,
        ConvertStart,
        ExtractStart,
        ExtractComplete,
        WriteEnd
    }
}